language: node_js
node_js: '6'
sudo: required
dist: trusty
addons:
  firefox: 52.3.0
  postgresql: '9.4'
  apt:
    packages:
    - dbus-x11
install:
- npm install
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database bitballs;' -U postgres
before_deploy:
- git config --global user.email "justin@bitovi.com"
- git config --global user.name "bitballs deploy bot"
- node public/build
- git add public/dist/ --force
- git commit -m "Updating build."
- npm run deploy:ci
deploy:
  skip_cleanup: true
  provider: heroku
  app: bitballs
  api_key:
    secure: XMm4TV8T+r2XFWdxJfQdPELKl0z08oyQLzkLgb13G3PWMqrtyF4u2Yx/c3Xxv2aT7HGOmsO1HZ4OLGvywmhIRgKbSIJpks/UU0DhH+gwtw1Y7LYCmbo2UCVTvle45Vg6M0LUWXS8ncWjHUr5ZyjbqHqpVRVqvebWBvD6f5NteZf2arKvJVvKzifSReAGfc/L22V3aCLYW57jKeo9RFG2SYGgCxn+Lqf2CEyxm0RARwOKNShqkzRvugvAJVCz2vkEEE8pvLBkc5KpjSqF60NbQGrXZvFELkk8OTx/7pc6DI3N9j4tcifkfzl8+AxXPpwyA/i9Jx6233STI44Y4JkwARYx/r7ylMj/s0f7tcO7RZVtga9zzMM5KmpX97nbXOYd6rS3qnKthoS/N/XXRFpTUxe4QYFtrjoQPo5HdUzaLarI0ehHFFJLhlUr55KPlufKcIjbD5a2aSkVIeb0sfN6uiQtKuz8c4kbZS+uGYd0F7B4pdxnPV1bh2FiuCUE6o44Ny2FVUb/BZSrtAVcO+jqhCaCb1JUTLPEhxV1UHIVsD1gSJAng23GphtHjdlh2uV2Vcy58Gx0BGkPHe25ypT5HsGnFQvECaT0fBd13thqr0MaBYxinRCUhF79crldd3D7LVT6RRENUFSQ2hpO0YqW028vUT+jm3DIugP5vEbnhkk=
env:
  global:
    secure: GtZ4Jqwgp5V9n+IC51FZT5KjIHMwmBXXntAyXCEQZopX0pGaya6IsJLvbQhkjFhBzJFnLVVkLbTpPaax8Gpf2a7Pwa/4ev8X7n1KxgTeupdpX7Ur8IO6np45n0o2BmE3l7+YOEzt6hC+rxYWPdcsVABTf8No5pPOVFgBL3GfM/fc2evn1wqJ5lGyPvQPJvJiRokznKxxnpqQ2W6C8P+LQy5v3iJJTqnNKWzJOj7dOPznOSdHA3sSJM+u/OjpyrPITsuXGTLXycMr/LK5jpyKUBIrFRZq7aY40+8hX8ZY+dMBHEuh7nIPHd45jqZx3Xk9Vgl974bWk1YK7ZqKk0HaveReqtprcKmEbc6toG22TFSyp3lcXkhLQV+wRWw0yrJ/czGbkuZU4jcO6r4ge75Bfi9+tUhqvMxk1sETkOunYoFpbyiUa7YU/ucH+hCcofphRH6NEtKdus749VdvcPu45rnL/zPxSs+5l8rpwWTp6XpcN0w8+MDYDhMSs6YPs9ltr0fP4U9amRjORU3PGkq7McAaXnenv3r2K5HSG8rFWTV5Te4ckj6MOIiU+tDSx0imClVccMr73NMJV0BVbkOWhef0uDlMb3uFFsPBj/t4OH1UkuhT+UeCNFCHxflj9aJEJe56NLD0ojZFeA1del7Cdl8yqWHL3b2sAkeRyWG09yM=
