language: node_js
node_js: '6'
sudo: required
dist: trusty
addons:
  firefox: 52.3.0
  postgresql: '9.4'
  apt:
    packages:
    - dbus-x11
install:
- npm install
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database bitballs;' -U postgres
before_deploy:
- git config --global user.email "justin@bitovi.com"
- git config --global user.name "bitballs deploy bot"
- node public/build
- git add public/dist/ --force
- git commit -m "Updating build."
- npm run deploy:ci
deploy:
  api_key:
    secure: G5xLgZeIDFhFjuBmq9RBDrQofyVI2v14eKdhCqH+U1WaVP4hhniGnxgDEjmilb6Zb7V9EPyyF5JNtHQgjIuJ06bK3dSSKpt3SLU74/w74EaQpdhxq7Xx+497xnBHfIhwA+8fg2RnLcppR2F+6IAYn55rfEIg92Cx81M/Cirm5sHccVQ6dV2/Sj2dWezAaG6VJQStH2z3E9ZwJrOd9wjf69H5KCG0onT2+syjs8EaE43QyBVo1GffhuEOaHrhI9vL19ctpOMTlzps3W3VE6sYr3LqFkxz+xPOstej++LqQSgdhheFh9F4H7NjsSc+9iZzM0KngHw0xKZ5b2mKZTBzR+u+JRpU30qLWmgcEV38z8i5SfOO8lPEHghh6msGbwZpVLPBLYRVnRWjAHHxslqaDEwNmb/2YdX9LTKdzsnFpYRGLVJIMGoCjTIvDV6lmyfMnxww8+W44Oh5Jh1XR5vkb6P0rIKTW3mwgx2o8vQcSRD+mUReCwA0EnLLaCBxZKG0Uku/zqe8skvFGVZMZfTBBMJ9GEIqPvh0ckYwGWcBmP+c+nFk+fxLl+3Fya86NWl1FaN/KeUIssmj/iVpsAy/nmVuPiwrgCnz+k0PG5WU3DbxiPVGn1+SlLQ/ncgu5yit0XfTiqAtt+FA/UxHTN5wZldvV/ppylTm36vWShqFKmI=
env:
  global:
    secure: bF4FoJFUqoc4YZAfrqh/G6Js945xeT34ZPRZgWV6/eY4hDWbTvfYD06cJL6HkAX42FIP8ZQaXoZTDC9bxr9F52FujXz+zdL0odW5cDl1K6tWb9Zhc+WVkmEouIKx8FLEt5flVFBm/L5VHoE92Lamuo+hvkuxrrM1gtskdYJhtsxy70ndLjajUohC60dgYFMrYjFVsFMFZRxDeNQ5ig8FkrFGdlFun83gd1/ZQerBHHug2hgjkdsUtLYB51OTsYRtDBEPPTXTh39WnhgqQGiEcdN5XnFh3hk4oSkbl+RKrBp1ML72oC9KC/aTbyUj27+0eOu55Px3vFYNF3jMwjcIC4EuiQqNQVhtU7zFCK0ubrqYXBCv93TkLXjScW1F0RKUyY0AKJ+5yXniML6zDFvbY7a7UW79Edx+eSJY41BYmBBQViQAgIIzcCsR6MKmG3aO4xZ77ILHeYn+3y6WEv8LdqruJLDlPc0B6E0z16PVC0dxIiH0pvDX9cg3uMLRS1W+5e+hXfQtTLOBdSfpYaoZbL+WEDV0koFJUzhmQgEKyRMUFzdgqC0+pBZUSETt1p5/U0TgCTrsqjpw4vq54rEfEosKPwLgPT0Xu9djJy0/sa56LbP+VPcJP0MAYsZjIex5iWDj+TTCkKXM8I/yAxsMzE5FRJMRHXGqdHtqjEBBCZs=
