language: node_js
node_js: '6'
sudo: required
dist: trusty
addons:
  firefox: 52.3.0
  postgresql: '9.4'
  apt:
    packages:
    - dbus-x11
install:
- npm install
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database bitballs;' -U postgres
before_deploy:
- git config --global user.email "justin@bitovi.com"
- git config --global user.name "bitballs deploy bot"
- node public/build
- git add public/dist/ --force
- git commit -m "Updating build."
- npm run deploy:ci
env:
  global:
    secure: sEeYTLsA7+R948JMZg6wHgSd2q7eHi6A+gcp131IiaLZ0fGS8UQ0lu8lJbd6pZZvj/BTk7BZhXvG+awL7ZpMI5VOKPDaaqeHwpbJ2BKSo3DJ9eR7upOb2jMFLVe48VCyHwNOvPzTiCGu5mrmahHhDkerGeJwiqP6vNinWAf0G/qyRKjoRuY0HRqqrye6fGaFkRw5yHZzNq/bDixbjnHbPPqe014GwZ+/6UTEa8Y9tczMEkwpfUpookQSSZQ7dv1RpPYDzkf4kgGhTjlpAQ3UCM2f7QrAsIpKG7UJRyiLUMkYkXSnsruFKK+VSUPr29sCo+262TeSLrvC8nwJ/l4rBYJAPCiork7eBuuAbHal1L4q7iXqFnFAy1bRpvnlFLKiMMJS3aN5e9Nw1C51LbfxARzxdGMmvH+bfgT1NnoPw2+eGnyb/tif2cl1VFHzMrJPkDdNmuCqKUAtYZk4L6ATaZB1AgyQyzdBe7uV6k+UUVk6TY+Y1J1YglFTJAsT6Za4Mzh28p+YciMLykywi63aIulHVvKr83RMHJkq5aCFKZF6g8mcpRZTc+ap5psURq6vwv4GHAzLW9QrG4Pams6o0iTUdFgx++h5HxIPJ430teKVKwsjGY9j/HLpDHJH+DZEHVQL+UKv4u8vh/2i0eIEhGvqWHa8GfCREhl2iqqqdxU=
deploy:
  api_key:
    secure: G5xLgZeIDFhFjuBmq9RBDrQofyVI2v14eKdhCqH+U1WaVP4hhniGnxgDEjmilb6Zb7V9EPyyF5JNtHQgjIuJ06bK3dSSKpt3SLU74/w74EaQpdhxq7Xx+497xnBHfIhwA+8fg2RnLcppR2F+6IAYn55rfEIg92Cx81M/Cirm5sHccVQ6dV2/Sj2dWezAaG6VJQStH2z3E9ZwJrOd9wjf69H5KCG0onT2+syjs8EaE43QyBVo1GffhuEOaHrhI9vL19ctpOMTlzps3W3VE6sYr3LqFkxz+xPOstej++LqQSgdhheFh9F4H7NjsSc+9iZzM0KngHw0xKZ5b2mKZTBzR+u+JRpU30qLWmgcEV38z8i5SfOO8lPEHghh6msGbwZpVLPBLYRVnRWjAHHxslqaDEwNmb/2YdX9LTKdzsnFpYRGLVJIMGoCjTIvDV6lmyfMnxww8+W44Oh5Jh1XR5vkb6P0rIKTW3mwgx2o8vQcSRD+mUReCwA0EnLLaCBxZKG0Uku/zqe8skvFGVZMZfTBBMJ9GEIqPvh0ckYwGWcBmP+c+nFk+fxLl+3Fya86NWl1FaN/KeUIssmj/iVpsAy/nmVuPiwrgCnz+k0PG5WU3DbxiPVGn1+SlLQ/ncgu5yit0XfTiqAtt+FA/UxHTN5wZldvV/ppylTm36vWShqFKmI=
